# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class LoginRequest(BaseModel):
    username: str
    password: str


class CreateBookingRequest(BaseModel):
    classId: str


class ChainProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: str
    name: str


class ApiError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str


class LocationProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: str
    name: str


class LoginResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accessToken: str


class ClassLocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: str
    studio: str
    room: str | None = None


class Activity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    description: str | None = None
    additionalInformation: str | None = None
    image: str | None = None


class Instructor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str


class SessionState(Enum):
    CONFIRMED = 'CONFIRMED'
    BOOKED = 'BOOKED'
    WAITLIST = 'WAITLIST'
    NOSHOW = 'NOSHOW'
    UNKNOWN = 'UNKNOWN'


class Status(Enum):
    BOOKED = 'BOOKED'
    WAITLIST = 'WAITLIST'


class BookingResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status
    positionInWaitList: int | None = None


class BranchProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    identifier: str
    name: str
    locations: list[LocationProfile]


class RezervoMirageClass(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    startTime: AwareDatetime = Field(..., examples=['2026-07-10T08:00:00.000Z'])
    endTime: AwareDatetime = Field(..., examples=['2026-07-10T08:00:00.000Z'])
    location: ClassLocation
    activity: Activity
    instructors: list[Instructor]
    isCancelled: bool
    cancelText: str | None = None
    totalSlots: int
    availableSlots: int
    waitingListCount: int
    bookingOpensAt: AwareDatetime = Field(..., examples=['2026-07-10T08:00:00.000Z'])


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: SessionState
    positionInWaitList: int | None = None
    class_: RezervoMirageClass = Field(..., alias='class')


class ChainResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    profile: ChainProfile
    branches: list[BranchProfile]


class ScheduleDay(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date: date_aliased = Field(..., examples=['2026-07-10'])
    classes: list[RezervoMirageClass]


class ScheduleResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    days: list[ScheduleDay]
