"""chain_user_optional_password

Revision ID: 0314e548f6d7
Revises: 4d51198ec426
Create Date: 2024-03-31 23:54:30.991946

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0314e548f6d7"
down_revision = "4d51198ec426"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chain_users", "password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chain_users SET password = '' WHERE password IS NULL")
    op.alter_column(
        "chain_users", "password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
