"""config unique user

Revision ID: 141159a3cb17
Revises: 44b71eadcdc6
Create Date: 2023-03-07 19:25:23.189041

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "141159a3cb17"
down_revision = "44b71eadcdc6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "configs", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "configs", type_="unique")
    # ### end Alembic commands ###
