"""rename_chain_id_ttt_to_3t

Revision ID: 1b3fb86758bf
Revises: b4aca3032fdf
Create Date: 2024-01-03 17:03:57.945448

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b3fb86758bf"
down_revision = "b4aca3032fdf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chain_users SET chain = '3t' WHERE chain = 'ttt'")
    op.execute("UPDATE recurring_bookings SET chain_id = '3t' WHERE chain_id = 'ttt'")
    op.execute("UPDATE sessions SET chain = '3t' WHERE chain = 'ttt'")
    op.execute(
        "UPDATE slack_class_notification_receipts SET chain = '3t' WHERE chain = 'ttt'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chain_users SET chain = 'ttt' WHERE chain = '3t'")
    op.execute("UPDATE recurring_bookings SET chain_id = 'ttt' WHERE chain_id = '3t'")
    op.execute("UPDATE sessions SET chain = 'ttt' WHERE chain = '3t'")
    op.execute(
        "UPDATE slack_class_notification_receipts SET chain = 'ttt' WHERE chain = '3t'"
    )
    # ### end Alembic commands ###
