"""add_last_used_to_push_notification_subscription

Revision ID: 270c2f0a9a5a
Revises: eeac56f2034e
Create Date: 2023-12-31 18:48:13.827683

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "270c2f0a9a5a"
down_revision = "eeac56f2034e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "push_notification_subscriptions",
        sa.Column("last_used", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("push_notification_subscriptions", "last_used")
    # ### end Alembic commands ###
