"""add auth lockout timestamp

Revision ID: 4f50495173a8
Revises: 1b3fb86758bf
Create Date: 2024-02-12 00:11:09.363916

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f50495173a8"
down_revision = "1b3fb86758bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_users", sa.Column("auth_lockout", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chain_users", "auth_lockout")
    # ### end Alembic commands ###
