"""user_chain_totp

Revision ID: 52c8a741cd0e
Revises: 5545c1fc35b6
Create Date: 2024-03-27 17:53:24.752372

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52c8a741cd0e"
down_revision = "5545c1fc35b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chain_users", sa.Column("totp", sa.String(), nullable=True))
    op.add_column(
        "chain_users", sa.Column("totp_verified_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chain_users", "totp_verified_at")
    op.drop_column("chain_users", "totp")
    # ### end Alembic commands ###
