"""use_mapped_columns

Revision ID: 5545c1fc35b6
Revises: cdf44f216db0
Create Date: 2024-02-28 00:29:51.740190

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5545c1fc35b6"
down_revision = "cdf44f216db0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "status",
        existing_type=postgresql.ENUM(
            "CONFIRMED",
            "BOOKED",
            "WAITLIST",
            "UNKNOWN",
            "PLANNED",
            "NOSHOW",
            name="sessionstate",
        ),
        nullable=False,
    )
    op.alter_column(
        "sessions",
        "class_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "user_relations",
        "relationship",
        existing_type=postgresql.ENUM(
            "UNKNOWN",
            "REQUEST_SENT",
            "REQUEST_RECEIVED",
            "FRIEND",
            name="userrelationship",
        ),
        nullable=False,
    )
    op.alter_column(
        "users",
        "preferences",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "users",
        "admin_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "admin_config",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "users",
        "preferences",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "user_relations",
        "relationship",
        existing_type=postgresql.ENUM(
            "UNKNOWN",
            "REQUEST_SENT",
            "REQUEST_RECEIVED",
            "FRIEND",
            name="userrelationship",
        ),
        nullable=True,
    )
    op.alter_column(
        "sessions",
        "class_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "sessions",
        "status",
        existing_type=postgresql.ENUM(
            "CONFIRMED",
            "BOOKED",
            "WAITLIST",
            "UNKNOWN",
            "PLANNED",
            "NOSHOW",
            name="sessionstate",
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
