"""lowercase_chain_identifier

Revision ID: 5e049d589d59
Revises: 818d1317e773
Create Date: 2023-12-25 01:05:08.579782

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "5e049d589d59"
down_revision = "818d1317e773"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chain_users SET chain = LOWER(chain)")
    op.execute("UPDATE sessions SET chain = LOWER(chain)")
    op.execute("UPDATE slack_class_notification_receipts SET chain = LOWER(chain)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE chain_users SET chain = UPPER(chain)")
    op.execute("UPDATE sessions SET chain = UPPER(chain)")
    op.execute("UPDATE slack_class_notification_receipts SET chain = UPPER(chain)")
    # ### end Alembic commands ###
