"""add scheduled reminder id to slack receipts

Revision ID: 7544ddc090a7
Revises: 32ee2ebb79d2
Create Date: 2023-10-19 15:09:52.710405

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7544ddc090a7"
down_revision = "32ee2ebb79d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "slack_class_notification_receipts",
        sa.Column("scheduled_reminder_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("slack_class_notification_receipts", "scheduled_reminder_id")
    # ### end Alembic commands ###
