"""slack_class_notification_receipt_integration_to_chain

Revision ID: 8823a3ebec51
Revises: b04ec6f8f6be
Create Date: 2023-12-23 23:56:26.118421

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8823a3ebec51"
down_revision = "b04ec6f8f6be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_class_notification_receipts", "integration", new_column_name="chain"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_class_notification_receipts", "chain", new_column_name="integration"
    )
    # ### end Alembic commands ###
