"""user-class sessions

Revision ID: 9936e1c8eab5
Revises: 09c91732a5b6
Create Date: 2023-05-25 22:38:34.065141

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9936e1c8eab5"
down_revision = "09c91732a5b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("class_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("CONFIRMED", "BOOKED", "WAITLIST", "UNKNOWN", name="sessionstate"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("class_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sessions")
    sa.Enum("CONFIRMED", "BOOKED", "WAITLIST", "UNKNOWN", name="sessionstate").drop(
        op.get_bind()
    )
    # ### end Alembic commands ###
