"""add_3t_identifier

Revision ID: a82b4e463f7d
Revises: 837322532df2
Create Date: 2023-10-08 20:00:35.474369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a82b4e463f7d"
down_revision = "837322532df2"
branch_labels = None
depends_on = None

original_integration_enum = sa.Enum("SIT", "FSC", name="integration")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE integration ADD VALUE 'TTT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE integration RENAME TO integration_old")
    original_integration_enum.create(op.get_bind())
    op.execute(("DELETE FROM integration_users WHERE integration = 'TTT'"))
    op.execute("DROP TYPE integration_old")
    # ### end Alembic commands ###
