"""rename_totp_verified_at_to_auth_verified_at

Revision ID: a959d99283df
Revises: 0314e548f6d7
Create Date: 2024-04-01 00:25:41.376805

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a959d99283df"
down_revision = "0314e548f6d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chain_users", "totp_verified_at", new_column_name="auth_verified_at"
    )
    op.execute(
        "UPDATE chain_users SET auth_verified_at = NOW() WHERE auth_verified_at IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chain_users", "auth_verified_at", new_column_name="totp_verified_at"
    )
    # ### end Alembic commands ###
