"""rename_totp_verified_at_to_auth_verified_at

Revision ID: a959d99283df
Revises: 0314e548f6d7
Create Date: 2024-04-01 00:25:41.376805

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a959d99283df"
down_revision = "0314e548f6d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_users", sa.Column("auth_verified_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("chain_users", "totp_verified_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chain_users",
        sa.Column(
            "totp_verified_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("chain_users", "auth_verified_at")
    # ### end Alembic commands ###
