"""session_integration_to_chain

Revision ID: b04ec6f8f6be
Revises: 361dceb969cb
Create Date: 2023-12-23 23:54:05.564189

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b04ec6f8f6be"
down_revision = "361dceb969cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sessions", "integration", new_column_name="chain")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("sessions", "chain", new_column_name="integration")
    # ### end Alembic commands ###
