"""add name to user

Revision ID: b795b5d14cf8
Revises: 9e4ae03dd225
Create Date: 2023-02-21 23:12:02.947098

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b795b5d14cf8"
down_revision = "9e4ae03dd225"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
