"""add integration auth token

Revision ID: bfe6318d5525
Revises: eaf4986cfa58
Create Date: 2023-08-29 16:49:17.432752

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfe6318d5525"
down_revision = "eaf4986cfa58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "integration_users", sa.Column("auth_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("integration_users", "auth_token")
    # ### end Alembic commands ###
