"""add noshow session state

Revision ID: cdf44f216db0
Revises: c08f9b7a41ff
Create Date: 2024-02-24 19:59:32.629176

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cdf44f216db0"
down_revision = "c08f9b7a41ff"
branch_labels = None
depends_on = None


original_session_status_enum = sa.Enum(
    "CONFIRMED", "BOOKED", "WAITLIST", "PLANNED", "UNKNOWN", name="sessionstate"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sessionstate ADD VALUE 'NOSHOW'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE sessionstate RENAME TO sessionstate_old")
    original_session_status_enum.create(op.get_bind())
    op.execute(
        (
            "ALTER TABLE sessions ALTER COLUMN status \
            TYPE sessionstate USING \
            case WHEN status = 'NOSHOW' THEN 'UNKNOWN'::sessionstate \
            ELSE status::text::sessionstate END"
        )
    )
    op.execute("DROP TYPE sessionstate_old")
    # ### end Alembic commands ###
