"""add_user_relation_table

Revision ID: de62bf59065d
Revises: 1b3fb86758bf
Create Date: 2024-02-08 20:58:19.979814

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de62bf59065d"
down_revision = "1b3fb86758bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_relation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_one", sa.UUID(), nullable=False),
        sa.Column("user_two", sa.UUID(), nullable=False),
        sa.Column(
            "relationship",
            sa.Enum(
                "UNKNOWN",
                "REQUEST_SENT",
                "REQUEST_RECEIVED",
                "FRIEND",
                name="userrelationship",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_one"], ["users.id"], ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_two"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id", "user_one", "user_two"),
        sa.UniqueConstraint("user_one", "user_two", name="unique_user_relation"),
    )
    op.create_index(op.f("ix_user_relation_id"), "user_relation", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_relation_id"), table_name="user_relation")
    op.drop_table("user_relation")
    # ### end Alembic commands ###
