"""add integration to sessions

Revision ID: eaf4986cfa58
Revises: 95f902617406
Create Date: 2023-08-28 14:56:55.875853

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eaf4986cfa58"
down_revision = "95f902617406"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "integration",
            postgresql.ENUM(name="integration", create_type=False),
            nullable=True,
        ),
    )
    op.execute("UPDATE sessions SET integration = 'SIT'")
    op.alter_column("sessions", "integration", nullable=False)
    op.drop_constraint("sessions_pkey", "sessions", type_="primary")
    op.create_primary_key(
        "sessions_pkey", "sessions", ["user_id", "integration", "class_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("sessions_pkey", "sessions", type_="primary")
    op.create_primary_key("sessions_pkey", "sessions", ["class_id", "user_id"])
    op.drop_column("sessions", "integration")
    # ### end Alembic commands ###
