"""integration_to_chain

Revision ID: fa1d494eb00d
Revises: 7544ddc090a7
Create Date: 2023-12-23 23:22:27.574606

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fa1d494eb00d"
down_revision = "7544ddc090a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "integration_users",
        "integration",
        existing_type=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "sessions",
        "integration",
        existing_type=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "slack_class_notification_receipts",
        "integration",
        existing_type=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "slack_class_notification_receipts",
        "integration",
        existing_type=sa.String(),
        type_=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        existing_nullable=False,
        postgresql_using="integration::integration",
    )
    op.alter_column(
        "sessions",
        "integration",
        existing_type=sa.String(),
        type_=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        existing_nullable=False,
        postgresql_using="integration::integration",
    )
    op.alter_column(
        "integration_users",
        "integration",
        existing_type=sa.String(),
        type_=postgresql.ENUM("SIT", "FSC", "TTT", name="integration"),
        existing_nullable=False,
        postgresql_using="integration::integration",
    )
    # ### end Alembic commands ###
