name: "rezervo"
services:
  db:
    container_name: rezervo-db
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - rezervo-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    env_file:
      - "../rezervo/db.env"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  db-admin:
    container_name: rezervo-db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 18000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.org
      PGADMIN_DEFAULT_PASSWORD: password
  rezervo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: rezervo
    # modified run server command with hot reloading
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8000:8000
    tty: true
    env_file:
      - "../rezervo/fusionauth.env"
    volumes:
      # mount source code as volume to allow hot reloading
      - "../rezervo:/app/rezervo"
      # app-wide configuration applied to all users
      - "../rezervo/config.json:/app/config.json:ro"
      # apprise config file
      - "../rezervo/apprise.yml:/app/config/apprise.yml:ro"
      - "rezervo-avatars:/app/content/avatars"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  auth-db:
    image: postgres:16.0-bookworm
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - rezervo-auth-data:/var/lib/postgresql/data
  auth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://auth-db:5432/fusionauth
      DATABASE_ROOT_USERNAME: postgres
      DATABASE_ROOT_PASSWORD: postgres
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://auth:9011
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart.json
    healthcheck:
      test: curl --silent --fail http://localhost:9011/api/status -o /dev/null -w "%{http_code}"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - 9011:9011
    env_file:
      - "../rezervo/fusionauth.env"
    volumes:
      - ./fusionauth-kickstart.json:/usr/local/fusionauth/kickstart.json:ro
      - rezervo-auth-config:/usr/local/fusionauth/config

volumes:
  rezervo-data:
  rezervo-avatars:
  rezervo-auth-data:
  rezervo-auth-config: