name: "rezervo"
services:
  db:
    container_name: rezervo-db
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - rezervo-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  db-admin:
    container_name: rezervo-db-admin
    image: dpage/pgadmin4
    restart: always
    ports:
      - 18000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.org
      PGADMIN_DEFAULT_PASSWORD: password
  rezervo:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: rezervo
    # modified run server command with hot reloading
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 8000:8000
    tty: true
    env_file:
      - "../rezervo/.env"
    volumes:
      # mount source code as volume to allow hot reloading
      - "../rezervo:/app/rezervo"
      # app-wide configuration applied to all users
      - "../rezervo/config.json:/app/config.json:ro"
      # supply env variables as file to allow access from cron
      - "../rezervo/.env:/app/.env:ro"
      - "rezervo-avatars:/app/content/avatars"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  rezervo-data:
  rezervo-avatars: