name: "rezervo"
services:
  db:
    container_name: rezervo-db
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - rezervo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: UPDATE_TO_SOMETHING_STRONG
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
#  db-admin:
#    container_name: rezervo-db-admin
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: your@fancy.email
#      PGADMIN_DEFAULT_PASSWORD: SURELY_SOMETHING_STRONG
  rezervo:
    container_name: rezervo
    image: ghcr.io/mathiazom/rezervo:main
    command: ["--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # app-wide configuration applied to all users
      - "./config.json:/app/config.json:ro"
      # supply env variables as file to allow access from cron
      - "./.env:/app/.env:ro"
      - "rezervo-avatars:/app/content/avatars"
volumes:
  rezervo-data:
  rezervo-avatars: