"""config cascade on user deletion

Revision ID: 44b71eadcdc6
Revises: a4c1db9f7b78
Create Date: 2023-03-07 19:21:35.920121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b71eadcdc6'
down_revision = 'a4c1db9f7b78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('configs_user_id_fkey', 'configs', type_='foreignkey')
    op.create_foreign_key(None, 'configs', 'users', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'configs', type_='foreignkey')
    op.create_foreign_key('configs_user_id_fkey', 'configs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
