BASE_PATH = "https://www.sats.no"

SCHEDULE_PATH = "/api/group-exercise-search-day"
LOGIN_PATH = "/logg-inn"
AUTH_PATH = "/api/log-in"
BOOK_PATH = "/api/book"
CANCEL_BOOKING_PATH = "/api/unbook"
BOOKINGS_PATH = "/min-side/kommende-trening"

SCHEDULE_URL = BASE_PATH + SCHEDULE_PATH
AUTH_URL = BASE_PATH + AUTH_PATH
BOOKING_URL = BASE_PATH + BOOK_PATH
UNBOOK_URL = BASE_PATH + CANCEL_BOOKING_PATH
BOOKINGS_URL = BASE_PATH + BOOKINGS_PATH
