name: Type check
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run mypy
        run: |
          poetry run mypy rezervo
